import 'dotenv/config'
import { PrismaMssql } from '@prisma/adapter-mssql'
import { PrismaClient } from '@prisma/client'

// Parsear DATABASE_URL: sqlserver://HOST:PORT;database=X;user=Y;password=Z;...
const raw = process.env.DATABASE_URL!
const [hostPart, ...paramParts] = raw.replace('sqlserver://', '').split(';')
const [host, port] = hostPart.split(':')
const params = Object.fromEntries(
    paramParts.filter(Boolean).map(p => p.split('=') as [string, string])
)

const pool = {
    server: host,
    port: Number(port) || 1433,
    user: params.user,
    password: params.password,
    database: params.database,
    options: {
        encrypt: params.encrypt === 'true',
        trustServerCertificate: params.trustServerCertificate === 'true',
    },
}

const adapter = new PrismaMssql(pool)
const prisma = new PrismaClient({ adapter })

async function main() {

    // ─── PAIS ────────────────────────────────────────────────────────────────────
    await prisma.pais.deleteMany()
    await prisma.pais.createMany({
        data: [
            { nombre: 'Argentina' }, { nombre: 'Bolivia' }, { nombre: 'Brasil' },
            { nombre: 'Chile' }, { nombre: 'Colombia' }, { nombre: 'Costa Rica' },
            { nombre: 'Cuba' }, { nombre: 'Ecuador' }, { nombre: 'El Salvador' },
            { nombre: 'Guatemala' }, { nombre: 'Honduras' }, { nombre: 'México' },
            { nombre: 'Nicaragua' }, { nombre: 'Panamá' }, { nombre: 'Paraguay' },
            { nombre: 'Perú' }, { nombre: 'República Dominicana' },
            { nombre: 'Uruguay' }, { nombre: 'Venezuela' },
        ],
    })

    const paisesCreados = await prisma.pais.findMany()
    const getId = (nombre: string) => paisesCreados.find((p: { id: number, nombre: string }) => p.nombre === nombre)!.id
    // ─── PROVINCIAS ──────────────────────────────────────────────────────────────
    await prisma.provincia.deleteMany()
    await prisma.provincia.createMany({
        data: [
            // Argentina
            { nombre: 'Buenos Aires', idPais: getId('Argentina') },
            { nombre: 'CABA', idPais: getId('Argentina') },
            { nombre: 'Catamarca', idPais: getId('Argentina') },
            { nombre: 'Chaco', idPais: getId('Argentina') },
            { nombre: 'Chubut', idPais: getId('Argentina') },
            { nombre: 'Córdoba', idPais: getId('Argentina') },
            { nombre: 'Corrientes', idPais: getId('Argentina') },
            { nombre: 'Entre Ríos', idPais: getId('Argentina') },
            { nombre: 'Formosa', idPais: getId('Argentina') },
            { nombre: 'Jujuy', idPais: getId('Argentina') },
            { nombre: 'La Pampa', idPais: getId('Argentina') },
            { nombre: 'La Rioja', idPais: getId('Argentina') },
            { nombre: 'Mendoza', idPais: getId('Argentina') },
            { nombre: 'Misiones', idPais: getId('Argentina') },
            { nombre: 'Neuquén', idPais: getId('Argentina') },
            { nombre: 'Río Negro', idPais: getId('Argentina') },
            { nombre: 'Salta', idPais: getId('Argentina') },
            { nombre: 'San Juan', idPais: getId('Argentina') },
            { nombre: 'San Luis', idPais: getId('Argentina') },
            { nombre: 'Santa Cruz', idPais: getId('Argentina') },
            { nombre: 'Santa Fe', idPais: getId('Argentina') },
            { nombre: 'Santiago del Estero', idPais: getId('Argentina') },
            { nombre: 'Tierra del Fuego', idPais: getId('Argentina') },
            { nombre: 'Tucumán', idPais: getId('Argentina') },
            // Bolivia
            { nombre: 'Beni', idPais: getId('Bolivia') },
            { nombre: 'Chuquisaca', idPais: getId('Bolivia') },
            { nombre: 'Cochabamba', idPais: getId('Bolivia') },
            { nombre: 'La Paz', idPais: getId('Bolivia') },
            { nombre: 'Oruro', idPais: getId('Bolivia') },
            { nombre: 'Pando', idPais: getId('Bolivia') },
            { nombre: 'Potosí', idPais: getId('Bolivia') },
            { nombre: 'Santa Cruz', idPais: getId('Bolivia') },
            { nombre: 'Tarija', idPais: getId('Bolivia') },
            // Brasil
            { nombre: 'Acre', idPais: getId('Brasil') },
            { nombre: 'Alagoas', idPais: getId('Brasil') },
            { nombre: 'Amapá', idPais: getId('Brasil') },
            { nombre: 'Amazonas', idPais: getId('Brasil') },
            { nombre: 'Bahia', idPais: getId('Brasil') },
            { nombre: 'Ceará', idPais: getId('Brasil') },
            { nombre: 'Distrito Federal', idPais: getId('Brasil') },
            { nombre: 'Espírito Santo', idPais: getId('Brasil') },
            { nombre: 'Goiás', idPais: getId('Brasil') },
            { nombre: 'Maranhão', idPais: getId('Brasil') },
            { nombre: 'Mato Grosso', idPais: getId('Brasil') },
            { nombre: 'Mato Grosso do Sul', idPais: getId('Brasil') },
            { nombre: 'Minas Gerais', idPais: getId('Brasil') },
            { nombre: 'Pará', idPais: getId('Brasil') },
            { nombre: 'Paraíba', idPais: getId('Brasil') },
            { nombre: 'Paraná', idPais: getId('Brasil') },
            { nombre: 'Pernambuco', idPais: getId('Brasil') },
            { nombre: 'Piauí', idPais: getId('Brasil') },
            { nombre: 'Rio de Janeiro', idPais: getId('Brasil') },
            { nombre: 'Rio Grande do Norte', idPais: getId('Brasil') },
            { nombre: 'Rio Grande do Sul', idPais: getId('Brasil') },
            { nombre: 'Rondônia', idPais: getId('Brasil') },
            { nombre: 'Roraima', idPais: getId('Brasil') },
            { nombre: 'Santa Catarina', idPais: getId('Brasil') },
            { nombre: 'São Paulo', idPais: getId('Brasil') },
            { nombre: 'Sergipe', idPais: getId('Brasil') },
            { nombre: 'Tocantins', idPais: getId('Brasil') },
            // Chile
            { nombre: 'Arica y Parinacota', idPais: getId('Chile') },
            { nombre: 'Tarapacá', idPais: getId('Chile') },
            { nombre: 'Antofagasta', idPais: getId('Chile') },
            { nombre: 'Atacama', idPais: getId('Chile') },
            { nombre: 'Coquimbo', idPais: getId('Chile') },
            { nombre: 'Valparaíso', idPais: getId('Chile') },
            { nombre: 'Metropolitana de Santiago', idPais: getId('Chile') },
            { nombre: "O'Higgins", idPais: getId('Chile') },
            { nombre: 'Maule', idPais: getId('Chile') },
            { nombre: 'Ñuble', idPais: getId('Chile') },
            { nombre: 'Biobío', idPais: getId('Chile') },
            { nombre: 'La Araucanía', idPais: getId('Chile') },
            { nombre: 'Los Ríos', idPais: getId('Chile') },
            { nombre: 'Los Lagos', idPais: getId('Chile') },
            { nombre: 'Aysén', idPais: getId('Chile') },
            { nombre: 'Magallanes', idPais: getId('Chile') },
            // Colombia
            { nombre: 'Amazonas', idPais: getId('Colombia') },
            { nombre: 'Antioquia', idPais: getId('Colombia') },
            { nombre: 'Arauca', idPais: getId('Colombia') },
            { nombre: 'Atlántico', idPais: getId('Colombia') },
            { nombre: 'Bolívar', idPais: getId('Colombia') },
            { nombre: 'Boyacá', idPais: getId('Colombia') },
            { nombre: 'Caldas', idPais: getId('Colombia') },
            { nombre: 'Caquetá', idPais: getId('Colombia') },
            { nombre: 'Casanare', idPais: getId('Colombia') },
            { nombre: 'Cauca', idPais: getId('Colombia') },
            { nombre: 'Cesar', idPais: getId('Colombia') },
            { nombre: 'Chocó', idPais: getId('Colombia') },
            { nombre: 'Córdoba', idPais: getId('Colombia') },
            { nombre: 'Cundinamarca', idPais: getId('Colombia') },
            { nombre: 'Guainía', idPais: getId('Colombia') },
            { nombre: 'Guaviare', idPais: getId('Colombia') },
            { nombre: 'Huila', idPais: getId('Colombia') },
            { nombre: 'La Guajira', idPais: getId('Colombia') },
            { nombre: 'Magdalena', idPais: getId('Colombia') },
            { nombre: 'Meta', idPais: getId('Colombia') },
            { nombre: 'Nariño', idPais: getId('Colombia') },
            { nombre: 'Norte de Santander', idPais: getId('Colombia') },
            { nombre: 'Putumayo', idPais: getId('Colombia') },
            { nombre: 'Quindío', idPais: getId('Colombia') },
            { nombre: 'Risaralda', idPais: getId('Colombia') },
            { nombre: 'San Andrés y Providencia', idPais: getId('Colombia') },
            { nombre: 'Santander', idPais: getId('Colombia') },
            { nombre: 'Sucre', idPais: getId('Colombia') },
            { nombre: 'Tolima', idPais: getId('Colombia') },
            { nombre: 'Valle del Cauca', idPais: getId('Colombia') },
            { nombre: 'Vaupés', idPais: getId('Colombia') },
            { nombre: 'Vichada', idPais: getId('Colombia') },
            // Costa Rica
            { nombre: 'Alajuela', idPais: getId('Costa Rica') },
            { nombre: 'Cartago', idPais: getId('Costa Rica') },
            { nombre: 'Guanacaste', idPais: getId('Costa Rica') },
            { nombre: 'Heredia', idPais: getId('Costa Rica') },
            { nombre: 'Limón', idPais: getId('Costa Rica') },
            { nombre: 'Puntarenas', idPais: getId('Costa Rica') },
            { nombre: 'San José', idPais: getId('Costa Rica') },
            // Cuba
            { nombre: 'Artemisa', idPais: getId('Cuba') },
            { nombre: 'Camagüey', idPais: getId('Cuba') },
            { nombre: 'Ciego de Ávila', idPais: getId('Cuba') },
            { nombre: 'Cienfuegos', idPais: getId('Cuba') },
            { nombre: 'Granma', idPais: getId('Cuba') },
            { nombre: 'Guantánamo', idPais: getId('Cuba') },
            { nombre: 'Holguín', idPais: getId('Cuba') },
            { nombre: 'La Habana', idPais: getId('Cuba') },
            { nombre: 'Las Tunas', idPais: getId('Cuba') },
            { nombre: 'Matanzas', idPais: getId('Cuba') },
            { nombre: 'Mayabeque', idPais: getId('Cuba') },
            { nombre: 'Pinar del Río', idPais: getId('Cuba') },
            { nombre: 'Sancti Spíritus', idPais: getId('Cuba') },
            { nombre: 'Santiago de Cuba', idPais: getId('Cuba') },
            { nombre: 'Villa Clara', idPais: getId('Cuba') },
            // Ecuador
            { nombre: 'Azuay', idPais: getId('Ecuador') },
            { nombre: 'Bolívar', idPais: getId('Ecuador') },
            { nombre: 'Cañar', idPais: getId('Ecuador') },
            { nombre: 'Carchi', idPais: getId('Ecuador') },
            { nombre: 'Chimborazo', idPais: getId('Ecuador') },
            { nombre: 'Cotopaxi', idPais: getId('Ecuador') },
            { nombre: 'El Oro', idPais: getId('Ecuador') },
            { nombre: 'Esmeraldas', idPais: getId('Ecuador') },
            { nombre: 'Galápagos', idPais: getId('Ecuador') },
            { nombre: 'Guayas', idPais: getId('Ecuador') },
            { nombre: 'Imbabura', idPais: getId('Ecuador') },
            { nombre: 'Loja', idPais: getId('Ecuador') },
            { nombre: 'Los Ríos', idPais: getId('Ecuador') },
            { nombre: 'Manabí', idPais: getId('Ecuador') },
            { nombre: 'Morona Santiago', idPais: getId('Ecuador') },
            { nombre: 'Napo', idPais: getId('Ecuador') },
            { nombre: 'Orellana', idPais: getId('Ecuador') },
            { nombre: 'Pastaza', idPais: getId('Ecuador') },
            { nombre: 'Pichincha', idPais: getId('Ecuador') },
            { nombre: 'Santa Elena', idPais: getId('Ecuador') },
            { nombre: 'Santo Domingo de los Tsáchilas', idPais: getId('Ecuador') },
            { nombre: 'Sucumbíos', idPais: getId('Ecuador') },
            { nombre: 'Tungurahua', idPais: getId('Ecuador') },
            { nombre: 'Zamora Chinchipe', idPais: getId('Ecuador') },
            // El Salvador
            { nombre: 'Ahuachapán', idPais: getId('El Salvador') },
            { nombre: 'Cabañas', idPais: getId('El Salvador') },
            { nombre: 'Chalatenango', idPais: getId('El Salvador') },
            { nombre: 'Cuscatlán', idPais: getId('El Salvador') },
            { nombre: 'La Libertad', idPais: getId('El Salvador') },
            { nombre: 'La Paz', idPais: getId('El Salvador') },
            { nombre: 'La Unión', idPais: getId('El Salvador') },
            { nombre: 'Morazán', idPais: getId('El Salvador') },
            { nombre: 'San Miguel', idPais: getId('El Salvador') },
            { nombre: 'San Salvador', idPais: getId('El Salvador') },
            { nombre: 'San Vicente', idPais: getId('El Salvador') },
            { nombre: 'Santa Ana', idPais: getId('El Salvador') },
            { nombre: 'Sonsonate', idPais: getId('El Salvador') },
            { nombre: 'Usulután', idPais: getId('El Salvador') },
            // Guatemala
            { nombre: 'Alta Verapaz', idPais: getId('Guatemala') },
            { nombre: 'Baja Verapaz', idPais: getId('Guatemala') },
            { nombre: 'Chimaltenango', idPais: getId('Guatemala') },
            { nombre: 'Chiquimula', idPais: getId('Guatemala') },
            { nombre: 'El Progreso', idPais: getId('Guatemala') },
            { nombre: 'Escuintla', idPais: getId('Guatemala') },
            { nombre: 'Guatemala', idPais: getId('Guatemala') },
            { nombre: 'Huehuetenango', idPais: getId('Guatemala') },
            { nombre: 'Izabal', idPais: getId('Guatemala') },
            { nombre: 'Jalapa', idPais: getId('Guatemala') },
            { nombre: 'Jutiapa', idPais: getId('Guatemala') },
            { nombre: 'Petén', idPais: getId('Guatemala') },
            { nombre: 'Quetzaltenango', idPais: getId('Guatemala') },
            { nombre: 'Quiché', idPais: getId('Guatemala') },
            { nombre: 'Retalhuleu', idPais: getId('Guatemala') },
            { nombre: 'Sacatepéquez', idPais: getId('Guatemala') },
            { nombre: 'San Marcos', idPais: getId('Guatemala') },
            { nombre: 'Santa Rosa', idPais: getId('Guatemala') },
            { nombre: 'Sololá', idPais: getId('Guatemala') },
            { nombre: 'Suchitepéquez', idPais: getId('Guatemala') },
            { nombre: 'Totonicapán', idPais: getId('Guatemala') },
            { nombre: 'Zacapa', idPais: getId('Guatemala') },
            // Honduras
            { nombre: 'Atlántida', idPais: getId('Honduras') },
            { nombre: 'Choluteca', idPais: getId('Honduras') },
            { nombre: 'Colón', idPais: getId('Honduras') },
            { nombre: 'Comayagua', idPais: getId('Honduras') },
            { nombre: 'Copán', idPais: getId('Honduras') },
            { nombre: 'Cortés', idPais: getId('Honduras') },
            { nombre: 'El Paraíso', idPais: getId('Honduras') },
            { nombre: 'Francisco Morazán', idPais: getId('Honduras') },
            { nombre: 'Gracias a Dios', idPais: getId('Honduras') },
            { nombre: 'Intibucá', idPais: getId('Honduras') },
            { nombre: 'Islas de la Bahía', idPais: getId('Honduras') },
            { nombre: 'La Paz', idPais: getId('Honduras') },
            { nombre: 'Lempira', idPais: getId('Honduras') },
            { nombre: 'Ocotepeque', idPais: getId('Honduras') },
            { nombre: 'Olancho', idPais: getId('Honduras') },
            { nombre: 'Santa Bárbara', idPais: getId('Honduras') },
            { nombre: 'Valle', idPais: getId('Honduras') },
            { nombre: 'Yoro', idPais: getId('Honduras') },
            // México
            { nombre: 'Aguascalientes', idPais: getId('México') },
            { nombre: 'Baja California', idPais: getId('México') },
            { nombre: 'Baja California Sur', idPais: getId('México') },
            { nombre: 'Campeche', idPais: getId('México') },
            { nombre: 'Chiapas', idPais: getId('México') },
            { nombre: 'Chihuahua', idPais: getId('México') },
            { nombre: 'Ciudad de México', idPais: getId('México') },
            { nombre: 'Coahuila', idPais: getId('México') },
            { nombre: 'Colima', idPais: getId('México') },
            { nombre: 'Durango', idPais: getId('México') },
            { nombre: 'Estado de México', idPais: getId('México') },
            { nombre: 'Guanajuato', idPais: getId('México') },
            { nombre: 'Guerrero', idPais: getId('México') },
            { nombre: 'Hidalgo', idPais: getId('México') },
            { nombre: 'Jalisco', idPais: getId('México') },
            { nombre: 'Michoacán', idPais: getId('México') },
            { nombre: 'Morelos', idPais: getId('México') },
            { nombre: 'Nayarit', idPais: getId('México') },
            { nombre: 'Nuevo León', idPais: getId('México') },
            { nombre: 'Oaxaca', idPais: getId('México') },
            { nombre: 'Puebla', idPais: getId('México') },
            { nombre: 'Querétaro', idPais: getId('México') },
            { nombre: 'Quintana Roo', idPais: getId('México') },
            { nombre: 'San Luis Potosí', idPais: getId('México') },
            { nombre: 'Sinaloa', idPais: getId('México') },
            { nombre: 'Sonora', idPais: getId('México') },
            { nombre: 'Tabasco', idPais: getId('México') },
            { nombre: 'Tamaulipas', idPais: getId('México') },
            { nombre: 'Tlaxcala', idPais: getId('México') },
            { nombre: 'Veracruz', idPais: getId('México') },
            { nombre: 'Yucatán', idPais: getId('México') },
            { nombre: 'Zacatecas', idPais: getId('México') },
            // Nicaragua
            { nombre: 'Boaco', idPais: getId('Nicaragua') },
            { nombre: 'Carazo', idPais: getId('Nicaragua') },
            { nombre: 'Chinandega', idPais: getId('Nicaragua') },
            { nombre: 'Chontales', idPais: getId('Nicaragua') },
            { nombre: 'Estelí', idPais: getId('Nicaragua') },
            { nombre: 'Granada', idPais: getId('Nicaragua') },
            { nombre: 'Jinotega', idPais: getId('Nicaragua') },
            { nombre: 'León', idPais: getId('Nicaragua') },
            { nombre: 'Madriz', idPais: getId('Nicaragua') },
            { nombre: 'Managua', idPais: getId('Nicaragua') },
            { nombre: 'Masaya', idPais: getId('Nicaragua') },
            { nombre: 'Matagalpa', idPais: getId('Nicaragua') },
            { nombre: 'Nueva Segovia', idPais: getId('Nicaragua') },
            { nombre: 'Río San Juan', idPais: getId('Nicaragua') },
            { nombre: 'Rivas', idPais: getId('Nicaragua') },
            { nombre: 'RACCN', idPais: getId('Nicaragua') },
            { nombre: 'RACCS', idPais: getId('Nicaragua') },
            // Panamá
            { nombre: 'Bocas del Toro', idPais: getId('Panamá') },
            { nombre: 'Chiriquí', idPais: getId('Panamá') },
            { nombre: 'Coclé', idPais: getId('Panamá') },
            { nombre: 'Colón', idPais: getId('Panamá') },
            { nombre: 'Darién', idPais: getId('Panamá') },
            { nombre: 'Herrera', idPais: getId('Panamá') },
            { nombre: 'Los Santos', idPais: getId('Panamá') },
            { nombre: 'Ngäbe-Buglé', idPais: getId('Panamá') },
            { nombre: 'Panamá', idPais: getId('Panamá') },
            { nombre: 'Panamá Oeste', idPais: getId('Panamá') },
            { nombre: 'Veraguas', idPais: getId('Panamá') },
            // Paraguay
            { nombre: 'Alto Paraguay', idPais: getId('Paraguay') },
            { nombre: 'Alto Paraná', idPais: getId('Paraguay') },
            { nombre: 'Amambay', idPais: getId('Paraguay') },
            { nombre: 'Asunción', idPais: getId('Paraguay') },
            { nombre: 'Boquerón', idPais: getId('Paraguay') },
            { nombre: 'Caaguazú', idPais: getId('Paraguay') },
            { nombre: 'Caazapá', idPais: getId('Paraguay') },
            { nombre: 'Canindeyú', idPais: getId('Paraguay') },
            { nombre: 'Central', idPais: getId('Paraguay') },
            { nombre: 'Concepción', idPais: getId('Paraguay') },
            { nombre: 'Cordillera', idPais: getId('Paraguay') },
            { nombre: 'Guairá', idPais: getId('Paraguay') },
            { nombre: 'Itapúa', idPais: getId('Paraguay') },
            { nombre: 'Misiones', idPais: getId('Paraguay') },
            { nombre: 'Ñeembucú', idPais: getId('Paraguay') },
            { nombre: 'Paraguarí', idPais: getId('Paraguay') },
            { nombre: 'Presidente Hayes', idPais: getId('Paraguay') },
            { nombre: 'San Pedro', idPais: getId('Paraguay') },
            // Perú
            { nombre: 'Amazonas', idPais: getId('Perú') },
            { nombre: 'Áncash', idPais: getId('Perú') },
            { nombre: 'Apurímac', idPais: getId('Perú') },
            { nombre: 'Arequipa', idPais: getId('Perú') },
            { nombre: 'Ayacucho', idPais: getId('Perú') },
            { nombre: 'Cajamarca', idPais: getId('Perú') },
            { nombre: 'Callao', idPais: getId('Perú') },
            { nombre: 'Cusco', idPais: getId('Perú') },
            { nombre: 'Huancavelica', idPais: getId('Perú') },
            { nombre: 'Huánuco', idPais: getId('Perú') },
            { nombre: 'Ica', idPais: getId('Perú') },
            { nombre: 'Junín', idPais: getId('Perú') },
            { nombre: 'La Libertad', idPais: getId('Perú') },
            { nombre: 'Lambayeque', idPais: getId('Perú') },
            { nombre: 'Lima', idPais: getId('Perú') },
            { nombre: 'Loreto', idPais: getId('Perú') },
            { nombre: 'Madre de Dios', idPais: getId('Perú') },
            { nombre: 'Moquegua', idPais: getId('Perú') },
            { nombre: 'Pasco', idPais: getId('Perú') },
            { nombre: 'Piura', idPais: getId('Perú') },
            { nombre: 'Puno', idPais: getId('Perú') },
            { nombre: 'San Martín', idPais: getId('Perú') },
            { nombre: 'Tacna', idPais: getId('Perú') },
            { nombre: 'Tumbes', idPais: getId('Perú') },
            { nombre: 'Ucayali', idPais: getId('Perú') },
            // República Dominicana
            { nombre: 'Azua', idPais: getId('República Dominicana') },
            { nombre: 'Bahoruco', idPais: getId('República Dominicana') },
            { nombre: 'Barahona', idPais: getId('República Dominicana') },
            { nombre: 'Dajabón', idPais: getId('República Dominicana') },
            { nombre: 'Distrito Nacional', idPais: getId('República Dominicana') },
            { nombre: 'Duarte', idPais: getId('República Dominicana') },
            { nombre: 'El Seibo', idPais: getId('República Dominicana') },
            { nombre: 'Elías Piña', idPais: getId('República Dominicana') },
            { nombre: 'Espaillat', idPais: getId('República Dominicana') },
            { nombre: 'Hato Mayor', idPais: getId('República Dominicana') },
            { nombre: 'Hermanas Mirabal', idPais: getId('República Dominicana') },
            { nombre: 'Independencia', idPais: getId('República Dominicana') },
            { nombre: 'La Altagracia', idPais: getId('República Dominicana') },
            { nombre: 'La Romana', idPais: getId('República Dominicana') },
            { nombre: 'La Vega', idPais: getId('República Dominicana') },
            { nombre: 'María Trinidad Sánchez', idPais: getId('República Dominicana') },
            { nombre: 'Monseñor Nouel', idPais: getId('República Dominicana') },
            { nombre: 'Monte Cristi', idPais: getId('República Dominicana') },
            { nombre: 'Monte Plata', idPais: getId('República Dominicana') },
            { nombre: 'Pedernales', idPais: getId('República Dominicana') },
            { nombre: 'Peravia', idPais: getId('República Dominicana') },
            { nombre: 'Puerto Plata', idPais: getId('República Dominicana') },
            { nombre: 'Samaná', idPais: getId('República Dominicana') },
            { nombre: 'San Cristóbal', idPais: getId('República Dominicana') },
            { nombre: 'San José de Ocoa', idPais: getId('República Dominicana') },
            { nombre: 'San Juan', idPais: getId('República Dominicana') },
            { nombre: 'San Pedro de Macorís', idPais: getId('República Dominicana') },
            { nombre: 'Sánchez Ramírez', idPais: getId('República Dominicana') },
            { nombre: 'Santiago', idPais: getId('República Dominicana') },
            { nombre: 'Santiago Rodríguez', idPais: getId('República Dominicana') },
            { nombre: 'Santo Domingo', idPais: getId('República Dominicana') },
            { nombre: 'Valverde', idPais: getId('República Dominicana') },
            // Uruguay
            { nombre: 'Artigas', idPais: getId('Uruguay') },
            { nombre: 'Canelones', idPais: getId('Uruguay') },
            { nombre: 'Cerro Largo', idPais: getId('Uruguay') },
            { nombre: 'Colonia', idPais: getId('Uruguay') },
            { nombre: 'Durazno', idPais: getId('Uruguay') },
            { nombre: 'Flores', idPais: getId('Uruguay') },
            { nombre: 'Florida', idPais: getId('Uruguay') },
            { nombre: 'Lavalleja', idPais: getId('Uruguay') },
            { nombre: 'Maldonado', idPais: getId('Uruguay') },
            { nombre: 'Montevideo', idPais: getId('Uruguay') },
            { nombre: 'Paysandú', idPais: getId('Uruguay') },
            { nombre: 'Río Negro', idPais: getId('Uruguay') },
            { nombre: 'Rivera', idPais: getId('Uruguay') },
            { nombre: 'Rocha', idPais: getId('Uruguay') },
            { nombre: 'Salto', idPais: getId('Uruguay') },
            { nombre: 'San José', idPais: getId('Uruguay') },
            { nombre: 'Soriano', idPais: getId('Uruguay') },
            { nombre: 'Tacuarembó', idPais: getId('Uruguay') },
            { nombre: 'Treinta y Tres', idPais: getId('Uruguay') },
            // Venezuela
            { nombre: 'Amazonas', idPais: getId('Venezuela') },
            { nombre: 'Anzoátegui', idPais: getId('Venezuela') },
            { nombre: 'Apure', idPais: getId('Venezuela') },
            { nombre: 'Aragua', idPais: getId('Venezuela') },
            { nombre: 'Barinas', idPais: getId('Venezuela') },
            { nombre: 'Bolívar', idPais: getId('Venezuela') },
            { nombre: 'Carabobo', idPais: getId('Venezuela') },
            { nombre: 'Cojedes', idPais: getId('Venezuela') },
            { nombre: 'Delta Amacuro', idPais: getId('Venezuela') },
            { nombre: 'Dependencias Federales', idPais: getId('Venezuela') },
            { nombre: 'Distrito Capital', idPais: getId('Venezuela') },
            { nombre: 'Falcón', idPais: getId('Venezuela') },
            { nombre: 'Guárico', idPais: getId('Venezuela') },
            { nombre: 'La Guaira', idPais: getId('Venezuela') },
            { nombre: 'Lara', idPais: getId('Venezuela') },
            { nombre: 'Mérida', idPais: getId('Venezuela') },
            { nombre: 'Miranda', idPais: getId('Venezuela') },
            { nombre: 'Monagas', idPais: getId('Venezuela') },
            { nombre: 'Nueva Esparta', idPais: getId('Venezuela') },
            { nombre: 'Portuguesa', idPais: getId('Venezuela') },
            { nombre: 'Sucre', idPais: getId('Venezuela') },
            { nombre: 'Táchira', idPais: getId('Venezuela') },
            { nombre: 'Trujillo', idPais: getId('Venezuela') },
            { nombre: 'Yaracuy', idPais: getId('Venezuela') },
            { nombre: 'Zulia', idPais: getId('Venezuela') },
        ],
    })

    // ─── AREA ────────────────────────────────────────────────────────────────────
    await prisma.area.deleteMany()
    await prisma.area.createMany({
        data: [
            { nombre: 'Ingeniería' },
            { nombre: 'Proyecto (Control y Gestión)' },
            { nombre: 'RRHH' },
            { nombre: 'Contabilidad / Finanzas' },
            { nombre: 'Business Intelligence' },
            { nombre: 'Geología' },
            { nombre: 'Calidad' },
            { nombre: 'IT' },
            { nombre: 'Administración' },
            { nombre: 'Otro' },
        ],
    })

    // ─── IDIOMA ──────────────────────────────────────────────────────────────────
    await prisma.idioma.deleteMany()
    await prisma.idioma.createMany({
        data: [
            { nombre: 'Inglés' },
            { nombre: 'Portugués' },
            { nombre: 'Francés' },
            { nombre: 'Italiano' },
            { nombre: 'Alemán' },
            { nombre: 'Mandarín' },
        ],
    })

    // ─── NIVEL EDUCATIVO ─────────────────────────────────────────────────────────
    await prisma.nivelEducativo.deleteMany()
    await prisma.nivelEducativo.createMany({
        data: [
            { nombre: 'Primario Completo' },
            { nombre: 'Secundario Incompleto' },
            { nombre: 'Secundario Completo' },
            { nombre: 'Técnico / Terciario' },
            { nombre: 'Universitario Incompleto' },
            { nombre: 'Universitario Completo' },
            { nombre: 'Posgrado / Maestría' },
        ],
    })

    // ─── TIPO CONVENIO ───────────────────────────────────────────────────────────
    await prisma.tipoConvenio.deleteMany()
    await prisma.tipoConvenio.createMany({
        data: [
            { nombre: 'Oficina' },
            { nombre: 'Operario' },
        ],
    })

    const convenios = await prisma.tipoConvenio.findMany()
    const idFueraConvenio = convenios.find((c: { id: number, nombre: string }) => c.nombre === 'Oficina')!.id
    const idOperario = convenios.find((c: { id: number, nombre: string }) => c.nombre === 'Operario')!.id

    // ─── LICENCIA ────────────────────────────────────────────────────────────────
    await prisma.licencia.deleteMany()
    await prisma.licencia.createMany({
        data: [
            { codigo: 'A', nombre: 'A – Motocicleta' },
            { codigo: 'B', nombre: 'B – Auto / Utilitario' },
            { codigo: 'C', nombre: 'C – Camión' },
            { codigo: 'D', nombre: 'D – Pasajeros' },
            { codigo: 'E', nombre: 'E – Maquinaria Pesada' },
        ],
    })

    // ─── PUESTO ──────────────────────────────────────────────────────────────────
    await prisma.puesto.deleteMany()
    await prisma.puesto.createMany({
        data: [
            { nombre: 'Herrero/Soldador' },
            { nombre: 'Carpintero' },
            { nombre: 'Maquinista' },
            { nombre: 'Mecánico' },
            { nombre: 'Topógrafo' },
            { nombre: 'Pañolero' },
            { nombre: 'Ayudante de obra' },
            { nombre: 'Casco verde' },
            { nombre: 'Electrico' },
            { nombre: 'Chofer (camión/sprinter)' },
        ],
    })

    // ─── HERRAMIENTAS ────────────────────────────────────────────────────────────
    await prisma.herramienta.deleteMany()
    await prisma.herramienta.createMany({
        data: [
            { nombre: 'AutoCAD' }, { nombre: 'Revit' }, { nombre: 'MS Project' },
            { nombre: 'Power BI' }, { nombre: 'SAP' }, { nombre: 'Excel avanzado' },
            { nombre: 'PVsyst' }, { nombre: 'Helioscope' }, { nombre: 'ETAP' },
            { nombre: 'AutoCAD Electrical' }, { nombre: 'Tableau' },
            { nombre: 'Primavera P6' }, { nombre: 'Python' }, { nombre: 'Power Apps' },
            { nombre: 'Power Automate' }, { nombre: 'Procore' }, { nombre: 'MATLAB' },
            { nombre: 'SCADA' }, { nombre: 'Google Workspace' },
            { nombre: 'Fusionadora de fibra óptica' }, { nombre: 'Telurímetro' },
            { nombre: 'Ensayo de resistencia de suelos' }, { nombre: 'Cono de arena' },
            { nombre: 'TH Hemitest' }, { nombre: 'Máquina SPT' },
            { nombre: 'Multímetro' }, { nombre: 'Pinza amperométrica' },
            { nombre: 'Megóhmetro' }, { nombre: 'Analizador de redes' },
            { nombre: 'Nivel óptico' }, { nombre: 'Estación total' },
            { nombre: 'GPS diferencial' }, { nombre: 'Durómetro' },
        ],
    })

    // ─── HABILIDADES ─────────────────────────────────────────────────────────────
    await prisma.habilidad.deleteMany()
    await prisma.habilidad.createMany({
        data: [
            // Fuera de Convenio - Ingeniería
            { nombre: 'Diseño estructural', idTipoConvenio: idFueraConvenio },
            { nombre: 'Cálculo de estructuras', idTipoConvenio: idFueraConvenio },
            { nombre: 'Diseño eléctrico BT/MT', idTipoConvenio: idFueraConvenio },
            { nombre: 'Ingeniería solar FV', idTipoConvenio: idFueraConvenio },
            { nombre: 'Gestión de obra', idTipoConvenio: idFueraConvenio },
            { nombre: 'Relevamiento topográfico', idTipoConvenio: idFueraConvenio },
            // Fuera de Convenio - Proyecto
            { nombre: 'Planificación de proyectos', idTipoConvenio: idFueraConvenio },
            { nombre: 'Control de avance', idTipoConvenio: idFueraConvenio },
            { nombre: 'Gestión de riesgos', idTipoConvenio: idFueraConvenio },
            { nombre: 'Presupuesto y costos', idTipoConvenio: idFueraConvenio },
            { nombre: 'PMI/PMBOK', idTipoConvenio: idFueraConvenio },
            { nombre: 'Reporting ejecutivo', idTipoConvenio: idFueraConvenio },
            { nombre: 'Metodologías ágiles', idTipoConvenio: idFueraConvenio },
            { nombre: 'Scrum', idTipoConvenio: idFueraConvenio },
            { nombre: 'Kanban', idTipoConvenio: idFueraConvenio },
            { nombre: 'SAFe', idTipoConvenio: idFueraConvenio },
            // Fuera de Convenio - RRHH
            { nombre: 'Liquidación de sueldos', idTipoConvenio: idFueraConvenio },
            { nombre: 'Selección de personal', idTipoConvenio: idFueraConvenio },
            { nombre: 'Capacitación', idTipoConvenio: idFueraConvenio },
            { nombre: 'Relaciones laborales', idTipoConvenio: idFueraConvenio },
            { nombre: 'Convenios colectivos', idTipoConvenio: idFueraConvenio },
            // Fuera de Convenio - Contabilidad / BI
            { nombre: 'Contabilidad general', idTipoConvenio: idFueraConvenio },
            { nombre: 'Auditoría', idTipoConvenio: idFueraConvenio },
            { nombre: 'Análisis financiero', idTipoConvenio: idFueraConvenio },
            { nombre: 'Power BI', idTipoConvenio: idFueraConvenio },
            { nombre: 'SQL', idTipoConvenio: idFueraConvenio },
            { nombre: 'ETL / Data warehouse', idTipoConvenio: idFueraConvenio },
            // Fuera de Convenio - Geología / Calidad
            { nombre: 'Estudio geotécnico', idTipoConvenio: idFueraConvenio },
            { nombre: 'Análisis de suelos', idTipoConvenio: idFueraConvenio },
            { nombre: 'Control de calidad', idTipoConvenio: idFueraConvenio },
            { nombre: 'ISO 9001', idTipoConvenio: idFueraConvenio },
            { nombre: 'Ensayos de materiales', idTipoConvenio: idFueraConvenio },
            // Fuera de Convenio - Administración
            { nombre: 'Gestión documental', idTipoConvenio: idFueraConvenio },
            { nombre: 'Compras', idTipoConvenio: idFueraConvenio },
            { nombre: 'Licitaciones', idTipoConvenio: idFueraConvenio },
            { nombre: 'Contratos', idTipoConvenio: idFueraConvenio },
            { nombre: 'Soporte IT', idTipoConvenio: idFueraConvenio },
            // Operario - Instalaciones Eléctricas
            { nombre: 'Cableado BT', idTipoConvenio: idOperario },
            { nombre: 'Cableado MT', idTipoConvenio: idOperario },
            { nombre: 'Instalación paneles solares', idTipoConvenio: idOperario },
            { nombre: 'Montaje de inversores', idTipoConvenio: idOperario },
            { nombre: 'Puesta a tierra', idTipoConvenio: idOperario },
            { nombre: 'Pruebas eléctricas', idTipoConvenio: idOperario },
            // Operario - Obra Civil
            { nombre: 'Albañilería', idTipoConvenio: idOperario },
            { nombre: 'Encofrado', idTipoConvenio: idOperario },
            { nombre: 'Hormigón', idTipoConvenio: idOperario },
            { nombre: 'Zanjeo', idTipoConvenio: idOperario },
            { nombre: 'Compactación', idTipoConvenio: idOperario },
            { nombre: 'Nivelación', idTipoConvenio: idOperario },
            { nombre: 'Montaje estructural', idTipoConvenio: idOperario },
            // Operario - Herrería y Metálica
            { nombre: 'Herrería', idTipoConvenio: idOperario },
            { nombre: 'Soldadura MIG', idTipoConvenio: idOperario },
            { nombre: 'Soldadura TIG', idTipoConvenio: idOperario },
            { nombre: 'Soldadura eléctrica', idTipoConvenio: idOperario },
            { nombre: 'Corte plasma', idTipoConvenio: idOperario },
            { nombre: 'Montaje metálico', idTipoConvenio: idOperario },
            // Operario - Maquinaria y Equipos
            { nombre: 'Operación de grúa', idTipoConvenio: idOperario },
            { nombre: 'Manejo de autoelevador', idTipoConvenio: idOperario },
            { nombre: 'Conducción camión', idTipoConvenio: idOperario },
            { nombre: 'Topografía básica', idTipoConvenio: idOperario },
            { nombre: 'Instrumentos de medición', idTipoConvenio: idOperario },
            // Operario - Mantenimiento
            { nombre: 'Mantenimiento eléctrico', idTipoConvenio: idOperario },
            { nombre: 'Mantenimiento mecánico', idTipoConvenio: idOperario },
            { nombre: 'Plomería', idTipoConvenio: idOperario },
            { nombre: 'Hidráulica', idTipoConvenio: idOperario },
            { nombre: 'Instrumentación', idTipoConvenio: idOperario },
            // Operario - Mecánica
            { nombre: 'Mecánica de autos', idTipoConvenio: idOperario },
            { nombre: 'Mecánica de maquinaria pesada', idTipoConvenio: idOperario },
            { nombre: 'Diagnóstico electrónico', idTipoConvenio: idOperario },
            { nombre: 'Reparación de motores', idTipoConvenio: idOperario },
            { nombre: 'Transmisiones y cajas', idTipoConvenio: idOperario },
            { nombre: 'Sistemas hidráulicos', idTipoConvenio: idOperario },
            { nombre: 'Frenos y suspensión', idTipoConvenio: idOperario },
            { nombre: 'Lubricación y filtros', idTipoConvenio: idOperario },
            { nombre: 'Rectificación de motores', idTipoConvenio: idOperario },
        ],
    })

    console.log('✅ Seed completado')
}

main()
    .catch(e => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })